ARG BASE_IMAGE=dataspace-workbench:1.0
FROM ${BASE_IMAGE}

ARG PIP_INDEX_URL=https://pypi.org/simple

RUN python -m pip install --no-cache-dir --index-url "${PIP_INDEX_URL}" \
        ipykernel==7.3.0 \
        jupyter_client==8.9.1 \
        jupyter_kernel_gateway==3.0.1

ENV HOME=/tmp
ENV JUPYTER_RUNTIME_DIR=/tmp/jupyter-runtime

WORKDIR /output
EXPOSE 8888
CMD ["jupyter", "kernelgateway", "--KernelGatewayApp.ip=0.0.0.0", "--KernelGatewayApp.port=8888"]
